name: Build

on:
  pull_request:
  workflow_dispatch:
    inputs:
        target:
            description: 'Task'
            required: true
            default: Default
            type: choice
            options:
                - Default
                - Clean
                - Restore
                - Build
                - Pack
                - Push

        pushToNuget:
            description: 'Push to Nuget'
            required: false
            default: false
            type: boolean

        logLevel:
            description: 'Verbosity'
            required: false
            default: Normal
            type: choice
            options:
                - Quiet
                - Minimal
                - Normal
                - Verbose
                - Diagnostic
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
    paths-ignore:
      - "README.md"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]

        name: ${{ matrix.os }}
        steps:
        - name: Setup net6.0
          uses: actions/setup-dotnet@v3.0.3
          with:
            dotnet-version: 6.x

        - name: Checkout
          uses: actions/checkout@v3.5.2
          with:
            fetch-depth: 0

        - name: Run the Cake script
          uses: cake-build/cake-action@master
          with:
            target: ${{ inputs.target || 'Default' }}
            verbosity: ${{ inputs.logLevel || 'Diagnostic' }}
            cake-version: tool-manifest
            arguments: |
                NUGET_PUSH: ${{ inputs.pushToNuget || false }}
                NUGET_URL: ${{ secrets.NUGET_URL }}
                NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
